### ISSUE TITLE
Greybel errors on passing non-empty lists with string literals and no parentheses

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#104]
```Lua
a = []
a.push ["p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]
```

Any string elements seem to upset the parser. Strange one

**Comment by ayecue** [comment]
There was a missing afterSpace check in the parser. Going to be fixed as soon https://github.com/ayecue/greybel-vs/pull/105 is merged.

**Comment by Olipro** [comment]
Looking good, thanks yet again
