### ISSUE TITLE
Uploading to "local" GreyHack breaks the game

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#108]
After running the Greybel build to upload to a `local` game session, everything seems to have gone fine.

However, when attempting to open `FileExplorer.exe` in GreyHack, you simply get a dialog reading `Error: device not found.`

This error can be resolved by quitting to Main Menu and re-entering the game. However, there are no files from Greybel present.

**Comment by ayecue** [comment]
Yeah sadly this cannot be fixed. The greybel-proxy package connects to the local game server and after it disconnects the game automatically kicks everyone with the same steamid. So essentially when greybel-proxy disconnects the server will also destroy the session for the actual game.

The same will happen when you have the game open online and run greybel-vs to upload a script there.

**Comment by Olipro** [comment]
I see, does this mean that `local` is entirely unusable or it is usable, if you go through a specific sequence of steps? What about the online/nightly options?

**Comment by ayecue** [comment]
So generally regardless of local, public or nightly after using the game file upload feature while having the game open you have to go back to the title screen and start a new game session. Of course if you are in singleplayer and upload files to public these sessions will not interfere.

The idea with keeping the session alive could work but might get a bit complex. But it's a suggestion maybe an improvement for the future.

**Comment by Olipro** [comment]
Hm, something is still amiss though. Even after going back to the main menu and re-entering, the files aren't present.

**Comment by ayecue** [comment]
Yeah I think I just found the issue. There is a limitation in the current client version which is used here. I'll create a fix.

**Comment by ayecue** [comment]
I've updated the client version to a newer one. Should be fixed with https://github.com/ayecue/greybel-vs/pull/113 merged.

**Comment by ayecue** [comment]
With 1.9.5 - https://github.com/ayecue/greybel-vs/pull/118 and the new GreyHack version both issues should be fixed.

The new GreyHack version seems to auto reconnect so you may have to close the open windows within the game since the session got renewed but beside of that everything should work alright. At least from my testing.

The client got updated to the latest version and should upload files of any size (obviously within the 160k limit) as expected.

**Comment by Olipro** [comment]
Excellent. One last thing:

Is there a "verbatim" option anywhere? I wrote myself a fairly rudimentary Ruby script a while ago that mostly does what you do by taking a list of file/dir arguments, collecting files together into `installer` file(s) that contain all the source code as strings to then emit them in-game - of course, it doesn't apply any transformations to the code at all, it is _verbatim_ byte-for-byte filename-for-filename with whatever the file contained.

Would it be possible (or is it already possible) to do this with Greybel and irrespective of _what_ the file's contents actually are (e.g. I also have random data files that aren't MiniScript, but they get dumped in all the same)

**Comment by ayecue** [comment]
Separate import command should be available now with 1.9.9
