### ISSUE TITLE
Multiline chained function invocations confuse the interpreter/debugger

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#109]
Given:

```Lua
Foo = {}
Foo.f = function(arg)
    return self
end function

Foo.f(1). // this is line 6
    f(2).
    f(3).
    f(1, 2). // wrong arg count
    f(3)
```

An error is reported to be on line 6. If you use `testlib` to automatically go into the debugger, it also is confused and doesn't see the attempt to invoke the function as the error.

**Comment by ayecue** [comment]
Thanks for reporting. I lately did some fixes related to function args maybe something broke. I'll take a look.

**Comment by ayecue** [comment]
Well technically it is correct since the statement starts at 6 and that's what the debugger shows at least that's how the current implementation works.

For the future I can take a look if there is any way to improve this logic to actually show the line of invocation and not the statement.

**Comment by Olipro** [comment]
Well, it's a little bit strange because, for example, if it forms part of the return statement, the top of the stack in the debug window says it's the return statement that's the issue, but I'd have expected it to be the evaluation of the function invocation.

Either way, pretty minor, just thought I'd let you know.

**Comment by ayecue** [comment]
With the new interpreter introduced with 2.1.0 the line in the stacktrace should be much more accurate.

**Comment by Olipro** [comment]
incredible, closing this one out.
