### ISSUE TITLE
Keys added to intrinsic types persist between runs

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#110]
I have a library which assigns various extension functions to the intrinsic maps like `list`, `map`, `number` etc. The code avoids doing any work by checking if one has already been defined.

Modifications to these intrinsics persist between runs, so the code sees the stuff from the previous run and does nothing.

For example, if you run the code `list.foo = 1` - this value will be accessible without having to define it on subsequent runs.

This also results in errors if you have an extension function that caches a handle to something like `print` since subsequent runs will be referencing a zombie `print` function connected to a dead terminal.

**Comment by ayecue** [comment]
That is a good point. It will only create intrinsics once when the wrapper classes are imported in JS. So I have to change the code to actually create a factory when the interpreter gets created. So each time a new interpreter gets created the intrinsics are fresh.

**Comment by ayecue** [comment]
I am now clearing the intrinsics on each start. Fix should be available after https://github.com/ayecue/greybel-vs/pull/113 is merged.

**Comment by Olipro** [comment]
Looking good, issue closed!
