### ISSUE TITLE
`hasIndex` chases the `__isa` chain

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#114]
Given:
```Lua
Foo = {}
Foo.b = 123
x = new Foo
print x.hasIndex("b")
```
`0` should be printed. MiniScript nor GreyScript chase the `__isa` chain.

**Comment by ayecue** [comment]
Hey nice find. I've changed the intrinsic to only look up the key within the actual map. Will be done with https://github.com/ayecue/greybel-vs/pull/116 merged.

**Comment by ayecue** [comment]
Bug should be fixed with 1.9.4 - https://github.com/ayecue/greybel-vs/pull/116 merged.

**Comment by Olipro** [comment]
We're Good to go.
