### ISSUE TITLE
`user_input` with `oneChar` == true doesn't catch certain keys or returns the wrong thing

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#124]
Not sure how much of a limitation you have with it being Javascript and all, but here's what I've found:

Backspace isn't caught at all.

Tab isn't caught.

Bizarrely, Delete, Insert, Home, End, PageUp & PageDown all instead give you `Escape`. Fortunately, Escape also gives you `Escape`. 😂 

Ctrl/Alt/Shift aren't caught at all - I'm putting these separately since they are special, and perhaps uncatchable.

**Comment by ayecue** [comment]
In case anyone is wondering. This was fixed with version 1.9.11.
