### ISSUE TITLE
`user_input` doesn't pass capital letters in single-char mode

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#130]
I suspect this is related to event firing.

When you press a special key, like `Shift` in GreyHack - it fires the event only ones, effectively "onKeyDown" and that is all. If the user keeps `Shift` held down, no events are fired, and subsequent calls will just return capital letters.

In Greybel, you do receive letters, but they are lower-case. This also happens even if Caps Lock is enabled.

**Comment by ayecue** [comment]
Should be resolved with https://github.com/ayecue/greybel-vs/pull/132 merged.

**Comment by Olipro** [comment]
champion, thanks again!
