### ISSUE TITLE
`user_input` prints certain regular chars as if they were special chars

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#134]
`.` results in `Delete`
`'` results in `RightArrow`
`#` results in `End`
`-` results in `Insert`
`!` results in `PageUp`
`"` results in `PageDown`
`$` results in `Home`
`%` results in `LeftArrow`
`&` results in `UpArrow`
`(` results in `DownArrow`

Everything else seems fine. Which surprised me as I was expecting `)` to do something weird, since `(` does, but nope, it's OK.

All chars were tested using a UK ISO-layout keyboard: https://i.stack.imgur.com/LcYFZ.png

**Comment by ayecue** [comment]
Yeah the implementation of key events was a bit odd. Key codes actually shared the same property with char codes which caused this issue. Same actually with the other key issue you opened a few days ago. I've now changed the implementation so this shouldn't happen anymore.

Should be resolved with https://github.com/ayecue/greybel-vs/pull/135
