### ISSUE TITLE
Unclosed formatting tag is printed to the terminal - at least for `user_input`

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#139]
In order to work around GreyHack making the terminal have a spasm when my interactive terminal prompt is at the bottom of the screen, I deliberately emit the unclosed tag `<line-height=0%>` at the end of the `user_input` string.

In Greybel this results in visibly printing `<line-height=0%></line-height>` to the terminal.

On a related note, `user_input` in single char mode won't receive a pasted string. This might be a bit difficult, but in-game even if it's in single-char mode, multiple chars will be returned if done via a paste operation.

**Comment by ayecue** [comment]
With https://github.com/ayecue/greybel-vs/pull/163 in place there should be now proper support for TextMesh Pro Rich-Text tags.

**Comment by ayecue** [comment]
With https://github.com/ayecue/greybel-vs/pull/203 the keypress input mode also received pasted strings. So with all these points fixed I'll close the ticket. In case I've missed something feel free to reopen.
