### ISSUE TITLE
Extension freeze when overwriting print

### ISSUE THREAD

**Issue by almostSouji** [ayecue/greybel-vs#172]
- Running the following via "Run File" results in no output and renders the entire plugin unusable for me.
(unable to run other/the same file (after changes), unable to open text preview, etc.)
- Even `Greybel: Refresh` does not resolve this
- The only resolution I have found so far is to fully re-install the extension

```lua
print = function(text)
    print("prefix " + text)
end function

print("hi")
```

Production use case: Altering the functionality of print to wrap in a standard output color. 
Current workaround: use arbitrary other function name

VSCode `1.85.1`
Greybel VS `v2.1.18`

**Comment by ayecue** [comment]
Thanks for reporting the issue. So in this case your code is actually causing an infinite loop. If you want to reassign print properly you would want to do the following:
```lua
originalPrint = @print

print = function(text, replaceText)
  originalPrint("<color=yellow>test</color>")
  originalPrint(text, replaceText)
end function

print("hello world")
```
Never the less though it would be more nice that the extension recovers and not just freezes VSCode. Therefore I'll tag this issue as an enhancement in regards of recovering when stuck in an infinite recursion call loop.

**Comment by almostSouji** [comment]
oh, that makes sense, thanks!
but yeah, recoverability would probably be the better UX

**Comment by ayecue** [comment]
`Greybel: Refresh` just refreshes the AST cache which is used for autocompletion, hover tips and other UI features.

**Comment by ayecue** [comment]
With 2.2.0 there is a frame limit in place which should prevent this kind of infinite recursion. Will close the ticket for now if there are any issues feel free to reopen this ticket.
