### ISSUE TITLE
Feature Request: Accessing within scope after instantiation code completion

### ISSUE THREAD

**Issue by Patrick-van-Halm** [ayecue/greybel-vs#27]
As a feature request it would be nice to have the code completion also keep in mind position of instantiation instead of just the scope.
Example:
```
// localScan() doesn't show here

localScan = function()
    test = true;
end function

// localScan() shows here
```

**Comment by ayecue** [comment]
With https://github.com/ayecue/greybel-vs/pull/28 merged autocomplete will now consider the position of a declaration of a variable.
