### ISSUE TITLE
Default args not printed when a funcRef is stringified

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#89]
In MiniScript (latest version or GreyHack) functions are printed with their default arguments included. Greybel doesn't do this.

Given: `f = function(a, b="foo"); end function; print @f`

MiniScript/GreyHack will print: `FUNCTION(a, b="foo")`

Greybel will print: `FUNCTION(a, b)`

Not a particularly huge issue, but I'm currently working on handling a pathological case in MiniMock where a function has a default argument containing a comma and needs to handle it in order to detect the correct parameter count.

**Comment by ayecue** [comment]
No worries I've added default values now to the function output. When it comes to literals the output going to be 1:1. But function references or other types will not be 1:1. Maybe I can improve that in the future.

Should be available as soon as https://github.com/ayecue/greybel-vs/pull/90 is merged.

**Comment by Olipro** [comment]
I don't think you'll ever need to do funcRefs anyway. It is an error in MiniScript to provide default arguments that aren't constant literals.

The MiniScript compiler from 2023 onwards throws an error if you do this. In older versions, it incorrectly exposes an internal constant that's unusable, essentially turning the parameter's value into garbage.

**Comment by ayecue** [comment]
Ah I mean I noticed that those types are just exposing useless internal constants but I wasn't aware that it was due to the MiniScript version. Just thought GreyScript added it's own logic to it. But good to know.

Should be available now. Can you can confirm that it works for you?

**Comment by Olipro** [comment]
Confirmed working. Thanks!
