### ISSUE TITLE
Execution continues after a call to exit() in a chained sequence

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#91]
Sorry to be piling on the issues, but I figured this one also deserved your attention.

Given:

```
f = {}

f.a = function()
    exit "bye"
end function

f.b = function()
end function

f.a.b

```

The interpreter will keep going and treat the call to `a` as if it returned null, printing an error to the console that `b` is unknown.

**Comment by ayecue** [comment]
Good find. The issue was that during a path resolve is going on it will not check for the interpreter state therefore just continuing.

Should be fixed when https://github.com/ayecue/greybel-vs/pull/90 is merged.

**Comment by ayecue** [comment]
https://github.com/ayecue/greybel-vs/pull/90 got merged. Can you please confirm it that fixed the issue for you?

**Comment by Olipro** [comment]
Also working, great!
