### ISSUE TITLE
Self-referential __isa or manually assigned __isa fails an isa check

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#92]
Given:

```
Foo = {}
Foo.__isa = Foo

if Foo isa Foo then print "yes"
```

This will evaluate to true in MiniScript but false in Greybel. Since MiniScript 2021 lacks the ability to compare by reference values, this is a space-efficient way of having a type-checkable object.

The following two cases also fail where they shouldn't

```
Foo = {}
Bar = new Foo
Bar = Bar + {}

if Bar isa Foo then print "yes"
```

```
Foo = {}
Bar = {"__isa": Foo}

if Bar isa Foo then print "yes"

```

**Comment by ayecue** [comment]
Nice find. Isa was handled a bit weirdly within the Greybel interpreter. I did some changes to it's general logic so it should be more accurate now.

This issue should be fixed as soon https://github.com/ayecue/greybel-vs/pull/90 is merged.

**Comment by ayecue** [comment]
https://github.com/ayecue/greybel-vs/pull/90 got merged. Can you please confirm it that fixed the issue for you?

**Comment by Olipro** [comment]
Working as well!
