### ISSUE TITLE
Incorrect scope resolution order

### ISSUE THREAD

**Issue by Olipro** [ayecue/greybel-vs#97]
Given:

```
globals.foo = function; print "global"; end function

bar = function()
	locals.foo = function; print "local"; end function
	inner = function()
		foo()
	end function
	inner
end function
bar
```
`local` should be printed as the lookup preference should be `locals` -> `outer` -> `globals`

**Comment by ayecue** [comment]
Appreciate all the reporting. PR with a fix is in place https://github.com/ayecue/greybel-vs/pull/98. Going to give an update as soon it's merged.

**Comment by ayecue** [comment]
PR got merged. Issue should be fixed now when you got time please confirm, thanks.

**Comment by Olipro** [comment]
Perfection, working as it should!
